# Generated by Django 3.1.7 on 2021-04-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WerkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('start_time', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werk.werkuser')),
            ],
        ),
    ]
