# Generated by Django 3.1.7 on 2021-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werk', '0002_werktask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werktask',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='werktask',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
