# Generated by Django 3.1.7 on 2021-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werk', '0004_auto_20210429_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werktask',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
