# Generated by Django 3.1.7 on 2021-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werk', '0005_auto_20210430_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werktask',
            name='end',
            field=models.TimeField(null=True),
        ),
    ]
