# Generated by Django 3.1.7 on 2021-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werk', '0008_auto_20210430_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werktask',
            name='total_time',
            field=models.DurationField(null=True),
        ),
    ]
